<?php
/**
 * @package     Wylia
 * @subpackage  Template File
 *
 * @copyright   Copyright (C) 2005 - 2013 Joomlashack. Meritage Assets.
 *              All rights reserved.
 * @license     GNU General Public License version 2 or later; see LICENSE.txt
 *
 * Do not edit this file directly. You can copy it and create a new file called
 * 'custom.php' in the same folder, and it will override this file. That way
 * if you update the template ever, your changes will not be lost.
 */
// no direct access
defined('_JEXEC') or die('Restricted access');

?>
<doctype>
<html>
    <head>
        <w:head />
    </head>
    <body class="<?php   echo $responsive . $fixedClass . $sidebarClass?>">
        <header id="header" class="z3 relative">
            <div class="<?php echo $containerClass ?>">
                <?php if ($this->countModules('toolbar')) : ?>
                <div class="wrapper-toolbar">
                    <w:nav containerClass="<?php echo $containerClass ?>" rowClass="<?php echo $gridMode;?>" wrapClass="navbar-fixed-top <?php echo $footerWrapperClass?>" type="toolbar" name="toolbar" />
                </div>
                <?php endif; ?>
                <?php if ($this->countModules('top')) : ?>
                <div id="top">
                    <div class="container-fluid">
                        <w:module type="row-fluid" name="top" chrome="wrightflexgrid" />
                    </div>
                </div>
                <?php endif; ?>
                <?php if ($this->countModules('menu') || $this->countModules('logo')) : ?>
                <div class="wrapper-logo-menu <?php echo $gridMode; ?> ">
                    <w:logo name="menu" menuWrapClass="navbar-inverse" type="menu"/>
                </div>
                <?php endif; ?>
           </div>
        </header>
        <div class="<?php echo $containerClass ?> background-white z1 absolute absolute-top absolute-left absolute-right"></div>
        <div class="<?php echo $containerClass ?> z2 relative">
            <div class="container-fluid">
                <?php if ($this->countModules('featured')) : ?>
                <!-- featured -->
                <div id="featured">
                    <w:module type="none" name="featured" chrome="xhtml" />
                </div>
                <?php endif; ?>
                <?php if ($this->countModules('grid-top')) : ?>
                <!-- grid-top -->
                <div id="grid-top">
                    <w:module type="row-fluid" name="grid-top" chrome="wrightflexgrid" />
                </div>
                <?php endif; ?>
                <?php if ($this->countModules('grid-top2')) : ?>
                <!-- grid-top2 -->
                <div id="grid-top2">
                    <w:module type="row-fluid" name="grid-top2" chrome="wrightflexgrid" />
                </div>
                <?php endif; ?>
                <?php if ($this->countModules('grid-top3')) : ?>
                <!-- grid-top3 -->
                <div id="grid-top3">
                    <w:module type="row-fluid" name="grid-top3" chrome="wrightflexgrid" />
                </div>
                <?php endif; ?>
                <?php if ($this->countModules('breadcrumbs')) : ?>
                <!-- breadcrumbs -->
                <div id="breadcrumbs">
                    <w:module type="single" name="breadcrumbs" chrome="none" />
                </div>
                <?php endif; ?>
                <div id="main-content" class="row-fluid">
                    <!-- sidebar1 -->
                    <aside id="sidebar1">
                        <w:module name="sidebar1" chrome="xhtml" />
                    </aside>
                    <!-- main -->
                    <section id="main">
                        <?php if ($this->countModules('above-content')) : ?>
                        <!-- above-content -->
                        <div id="above-content">
                            <w:module type="none" name="above-content" chrome="xhtml" />
                        </div>
                        <?php endif; ?>

                        <?php if ($moduleMain) : ?>
                        <w:module type="none" name="main" chrome="xhtml" />
                        <?php else : ?>
                        <!-- component -->
                        <w:content />
                        <?php endif; ?>
                    </section>
                    <!-- sidebar2 -->
                    <aside id="sidebar2">
                        <w:module name="sidebar2" chrome="xhtml" />
                    </aside>
                </div>
                <?php if ($this->countModules('below-content')) : ?>
                <!-- below-content -->
                <div id="below-content">
                    <w:module type="none" name="below-content" chrome="xhtml" />
                </div>
                <?php endif; ?>
                <?php if ($this->countModules('grid-bottom')) : ?>
                <!-- grid-bottom -->
                <div id="grid-bottom" >
                    <w:module type="row-fluid" name="grid-bottom" chrome="wrightflexgrid" />
                </div>
                <?php endif; ?>
                <?php if ($this->countModules('grid-bottom2')) : ?>
                <!-- grid-bottom2 -->
                <div id="grid-bottom2" >
                    <w:module type="row-fluid" name="grid-bottom2" chrome="wrightflexgrid" />
                </div>
                <?php endif; ?>
            </div>
        </div>
        <!-- footer -->
        <div class="wrapper-footer<?php echo $footerWrapperClass?>">
            <footer id="footer" <?php if ($this->params->get('stickyFooter',1)) : ?> class="sticky z3 relative" <?php else : ?>class="z3 relative"<?php endif;?>>
                <hr class="hr-footer">
                <div class="<?php echo $containerClass ?>">
                <div class="container-fluid">
                    <?php if ($this->countModules('grid-bottom3')) : ?>
                    <!-- grid-bottom3 -->
                    <div id="grid-bottom3" >
                        <w:module type="row-fluid" name="grid-bottom3" chrome="wrightflexgrid" />
                    </div>
                    <?php endif; ?>
                    <?php if ($this->countModules('bottom-menu')) : ?>
                    <!-- bottom-menu -->
                    <w:nav containerClass="contaniner-fluid" rowClass="row-fluid" name="bottom-menu" />
                    <?php endif; ?>
                    <?php if ($this->countModules('footer')) : ?>
                    <w:module type="<?php echo $gridMode; ?>" name="footer" chrome="wrightflexgrid" />
                    <?php endif; ?>
                    <w:footer />
                </div>
                </div>
            </footer>
        </div>

        <script type='text/javascript' src='<?php echo JURI::root(true) ?>/templates/js_wylia/js/wylia.js'></script>
        <?php
            $browser = JBrowser::getInstance();

            if ($browser->getBrowser() == 'msie')
            {
                $major = $browser->getMajor();

                if ((int)$major <= 9) {
                    echo "<script type='text/javascript' src='" . JURI::root() .  "templates/" . $this->document->template . "/js/jquery.equalheights.js'></script>";
                    echo "<script type='text/javascript' src='" . JURI::root() .  "templates/" . $this->document->template . "/js/fallback.js'></script>";
                }

            }
        ?>
    </body>
</html>

